sudo: required
dist: trusty
group: edge

language:
  - generic

services:
  - docker

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_TEX=$CACHE_DIR/tex.tar.gz

cache:
  directories:
  - $CACHE_DIR

before_install:
  - if [ -f ${CACHE_FILE_TEX} ]; then gunzip -c ${CACHE_FILE_TEX} | docker load; fi

script:
  - cd src
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex
  - mkdir -p $CACHE_DIR
  - if [ ! -f ${CACHE_FILE_TEX} ]; then docker save harshjv/texlive-2015 | gzip > ${CACHE_FILE_TEX}; fi

deploy:
  provider: releases
  api_key:
    secure: kLuWUIDQe9v8sIRD/4B0bHl43V9sezgThyxt/y06AhKY2Rv8ny4zF2VQiapFEDgr6xbjEpEulfKEiuLL4xXDF1pnXVCOJBfosUafkMb0SOXylF/uEmCZfRi587HcUjsCVU/FpdbQtfCZaup3FG61r1Dzjt0H/iqoj1V15PCdLkLgagEHSTp+bNYDAq9SHjrHJc1Q6hh/3LxvujtNvafgd29OvuAmNyYFE7tcVFnd2fmW6It+PTbnB/VzQKZhibwaPKkoxjShUBRtnxdPAUgqTXRb8T6tgr123+MfQnf+c2BzoLwA6wzlucXPVbh5s5eq2DpHOkGrOJJFmqIpMuQEsY19UT+YhcrpUqFqLLI7VgEdYUpau0DyrxzkQSo2er+Ycauz3pBuohfGnx81zeduAbFvc36WPuKdiIkWMfxStjAlE5YVwgtgNyKHNiwZOgo7tY6YotUYNCgToD7IznbEriUpb/a3kPocucJoBXN9V56x/1z+Gv7PFed+1vqzkZfTIYi0iDapZi5h3hL8ijuCJQ8Zwn8Q/J4sS/rqMAqxRyrX9UPPVkN8yzpltpst0rSCA8HHGgORePbWwOHAD9GrQxlRzjkZynOAj3h5z0Ww4TJ+QAZH/A8EoKUsbE8fImAV4jT/FqfWrfT/BkbXyOfYeTPzrsDS8uXLpPb0mGyTyY8=
  file: cv.pdf
  on:
    tags: true
