sudo: required
dist: trusty
group: edge

language:
  - generic

services:
  - docker

script:
  - cd src
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex

deploy:
  provider: releases
  api_key:
    secure: "iM9dkx1KmRw50++9d2qoFhttsRYN/SVbXYNKGrKIj/V4OYaVd6IVJKVVUOt2ktyE1UjzAE32aOVsaFEeM0+Uu2SFqFcpuuYpN1RqKsb/cmIlOJzBbL7kK14D5Pl6Kf53+pEHvcsavnzlVdNKra11A6bZk7N2hw4h6xbYzNhtriWYbJfqPkr/RCPAim8sBGWngM0BNrw733CDt5fOohD4+kylcQVEbGbf0iubFiJdtD+ruGte8km+0KrKYoLZW+26pFbP09ovwKyiPNaJv0dOFBVqbRK8yKTH3GdQl1SEt/Z11r4bMiP4o6LBm390MeaAIZ0VsTu1Q/2DJUDA7CZ3R38COASXZbsFzK88dZJqpJjxG1JDA/tQ/bw9VhPVvpcvGBWFsiOmd6Xxh9ZPqxyPyMuoT99sjwTIEzOLDxYNMEsiGRBOUO3MygEoUfBmTFova0tYkg+N2GcGtWFNRUm7f1qozvXpEbg7SYDIPM/JFYAlS1ljkBm4ImijQAOY9u0zyFbE5c2ru04Un944jV+Ie6Skvxrmxdojx7uyiH2yhwcfuX+znpFZWupjE9hgc13W363zyduCWxaFQLApjCTvSs3vNZvNcrOu9PyJc3HvfJIxMsg3ZK0dfKHgLXY6iCAxjCksdZlJDP5fcMObeZT71bSOMHrZQ/LPtVJ9ltvUegs="
  file: "cv.pdf"
  skip_cleanup: true
  on:
    tags: true
