sudo: required
dist: trusty
group: edge

language:
  - generic

services:
  - docker

script:
  - cd src
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex

deploy:
  provider: releases
  api_key:
    secure: "Q6cL7oprPYRl8WR7mldVS8KJH0hS2/p0B5fRoy37/WfSRE3qUe79RR37XBFUPRu/syH9HyWeuBx1DRq8+rj6zKlG6avencUIpEEe6bxoeSnXKh1/CbZgBFutF0PZ1TWEyROR+KVipUfP1bTudhIp4hvYXhYWwrwVrtit8HOadp3YnG+xVqpqplj45aGN9jgoe75hRVtXGDJMcWwD47FiEoA+MqOW8GKEQ9YCdDpzspcIVSir/reWZGAAyAHMj1rMNFSdbZvG8PfJymNMbtcVETBrUSuvoEOwLbzSOViOBvAproZR4TaPVpBnGqwPWtXzTHEIrm5he/dhZPnmsheDD5WNR68FzJ7h7aQY5o8SzwmoxIo674FN+Uc+NbJQJt1ygBpX9AZHk7RjPYscVrvOBVxUoiPN8CP7TR63lxdE+QpUwt1bw2Oby2z5A4o+FboP0Fo/Suex44R51oM6MP1tLAwcdFVPtlz2UUvWFb5DhYIvjv7qhNN3ZGNFmMeAEqj5BAWAbUmrg/VMUTFczRSYFQceEaSNbJLO7GjTJlcOWnAdVIABzzPlkec+RXtWahI8NrCmaOBC/Leighw2XHYTzpfVGqzW9bpuQtW6Vd7ViEe4TzG2fbwJpziDqpSwwL34BXKUwc1rXQ70fXl/vkZnp8Rfjvzk8yiVIIGceRkxMD4="
  file: "cv.pdf"
  skip_cleanup: true
  on:
    tags: true
