sudo: required
dist: trusty
group: edge

language:
  - generic

services:
  - docker

script:
  - cd src
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex

deploy:
  provider: releases
  api_key:
    secure: "t9DUi/Am8R1WXTymLfWH2SuXNy5WLs/jsJQBpOGlaXdK7Jb7iANiU++BTrNW0LwlwakYqO0MiQmTUpDqLVkGzvqNwdsqja542+QMzmc/PjKm4cFg5L/bSwOrkIgUvsTyvPrUJbBD/ZTEQS4Pk4lAquMy+ar8apKuTWikVNIcZkiMovnHqi7y1mPqCd0NQwf7/xqGwmpdDptJ2NN70K7gdFHuuqRseDWy+w8CZ0nj2t5in9xay6ssFAxroGKsufBAS9cc/PWEelKsk/wp0OJTYMnOC5ddx6vbh4D7xfvA8epIba8lzIwkl+y2oC8hzuaXizzKVdLjv5VTyth3cw2I+Uy6SC+iP7mCOrbsCUlybG9Ub/36goPtbkawmL5Er65U/+KD+a+41zBOYUmSg/3Gd5/en3PlrbPkqd0F8XWyGJ38Oj0raR2TnyVsvklvsro+aUf+6krE+oYLG9jgDTYo7xCj/BPx8ix1P/lLRK1X+9aaWt1M7kUugVktacrxTPJnL/W8dBGoGudc1Nh3n6YEd5Il3S3jk3OKLhNWf73xEV7/E4QBypn6NOuzFlB2ehd6Md63zGcPBfvtzGfLqhm1Tjc9+nJC82OzLAxR6atXywVYDPYIHEYTwFaU5OLJ+EhiXTOxUBRegpJF+kV7/kg0bfnyqow5XY/MJmA+TSJuc9I="
  file: "cv.pdf"
  skip_cleanup: true
  on:
    tags: true
