sudo: required
dist: trusty
group: edge

language:
  - generic

services:
  - docker

script:
  - cd src
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex

deploy:
  provider: releases
  api_key:
    secure: "DyIO5A+pMrE208RQabhdHyKUkJmaMj9JFHiEWWcZX0ow+NrPUCBZmHEVsBnaO27fLVA6/qedvJNMc7aq/XDc1gP46LsTKFptBPxhJ5lV5EzIqLMvffSrUaYDIyQXOZqi8X9miYlYfgPhitUhkKKxmBMb87Zlz+6qDYZDymFJl4ZoBx7Uj2VpgBp1wqkWJrv3gfG7+vVhB2f+PjUDFAt6PcmEKukBiBulp2QPGEFuO98qv6OptowKXGHRQZo86osn2SYUBlEtNeYUE4uH9lj8MWc5jZCLs4RDKpO9qkgVolCss+EFdijO4OiT0lqCg2PM84Kz03Uf7fkACCS2v1coy5wyoNbVGfMBgvjX5CBxOZGv9uRmelUN3mO2XG4mfafHQZSVQGZ9Nm7MpUT0GNt8EI9xKS0PODWl2HvoSXp7OCuHUHd1Lec6GwZ2H0vCnSZotAqw0ueCjZIX2p4j7k8LF8j/CNxNQFCVUDYpdBzQipMXmlDHz642sarTr0yD1X9iqQ2KVRfCq7M2lXl0pQQNA31tKP6/K3xw//db78rGiD2ulH/Qlf95oQ3kxb67yhZuRgtPtOniRP3u5iP0ozyukY4b5W/mFzj3whRoqxZ7ghXh1N4lD6X00NL0oDXnukSJNJJDeeLr0KySjPtX345zKFczPH2YGGxZ+RQLFD9sI8M="
  file: "cv.pdf"
  skip_cleanup: true
  on:
    tags: true
